name: sdk-bsp-stm32mp157a-st-dk1

on:
  schedule:
    # Runs at 00:00 UTC on the 1, 6, 11, 16, 21, 26 and 31th of every month
    - cron:  '0 0 */5 * *'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Check Package Yaml
      run: |
        pip install rt-thread-studio
        python -c "from rt_thread_studio import bsp_checker;bsp_path = '.';checker = bsp_checker.BspChecker(bsp_path);checker.check();" 
